development:
  sessions:
    default:
      hosts:
      - localhost:27017
      database: discover_development

test:
  sessions:
    default:
      hosts:
      - localhost:27017
      database: discover_test

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true
